export type GamePhase =
  | "WAITING"
  | "WEREWOLF_SELECTION"
  | "SECRET_RULE_SELECTION"
  | "PLAYING"
  | "DISCUSSION"
  | "WEREWOLF_VOTING"
  | "SECRET_RULE_GUESS"
  | "REVEAL"
  | "HIDDEN_SCORE_SETTLEMENT"
  | "NEXT_ROUND"
  | "FINISHED";
